name: FABULOUS
channels:
  - pytorch
  - anaconda
  - base
  - omnia
  - plumed
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - astor=0.8.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - blosc=1.16.3
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - colorama=0.4.3
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - gast=0.3.3
  - grpcio=1.12.1
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-gpu=2.3.1
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libsodium=1.0.16
  - lz4-c=1.8.1.2
  - lzo=2.10
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mdtraj=1.9.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=4.0.2
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - notebook=6.0.3
  - numexpr=2.7.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - protobuf=3.11.4
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pytables=3.6.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=47.1.1
  - sip=4.19.13
  - six=1.15.0
  - snappy=1.1.7
  - sqlite=3.31.1
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - maps==5.1.1

