keep_atoms: backbone

network_config:
  n_layers: [4]
  batch_size: [8000]
  optimizer: [adam]
  epochs: [500]

layer_config:
  layer_type:
    - dense
    - dropout
    - batch_norm
  n_nodes: [8, 16, 64]
  activation:
    - selu
    - linear
    - relu
  dropout: [0.2]

optimizer:
  pop_size: 50
  train_verbose: 0
  reject_select_chance: 0.05
  retain: 0.02
  early_stopping: true
  mutation_rate: 0.1
  penalty: 0.15
  parent_frac: 0.1
  cache: true
  train_chance: 0.1
  val_split: 0.3
